'use client';
import {useEffect,useRef,useState} from 'react';
import './planning-panel.css';
import {ArrowDown,ArrowUp,CalendarClock,Check,MapPin,Route,Search,ShieldCheck,X} from 'lucide-react';
import type {Coordinates,Mode,Precision} from '@/lib/types';
import type {AddressCandidate,LocationPoint,MeetingPlan,PlanInput,PlanningOrganization,PlanningPayload} from '@/lib/planning-types';
import {nextWeekdayStart} from '@/lib/planning-time';

type Props={mode:Mode;snapshot?:string;initialOrganizationId?:string;onOrganization?:(id:string)=>void;onRoute?:(plan:MeetingPlan|null)=>void;onRequestWork?:()=>void};
async function read<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{cache:'no-store',...init});const body=await response.json();if(!response.ok)throw new Error(body.error||'Не удалось выполнить действие. Повторите попытку.');return body as T;}
const post=<T,>(url:string,body:unknown)=>read<T>(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const clock=(value:string)=>new Date(value).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'});
const pointLabel=(org:PlanningOrganization)=>org.location?.meeting?.address||org.location?.office?.address||org.location?.legalAddress?.address||'Адрес пока не определён';
const locationLabels={verified:'Подтверждено пользователем',source_exact:'Совпадение ИНН',candidate:'Адрес требует подтверждения',unlocated:'Адрес не определён'};

export default function PlanningPanel({mode,snapshot='current',initialOrganizationId,onOrganization,onRoute,onRequestWork}:Props){
  const [data,setData]=useState<PlanningPayload|null>(null),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[locatedOnly,setLocatedOnly]=useState(false);
  const [tab,setTab]=useState<'organizations'|'plan'>('organizations'),[selected,setSelected]=useState<PlanningOrganization[]>([]),[editing,setEditing]=useState<PlanningOrganization|null>(null),[preview,setPreview]=useState<MeetingPlan|null>(null);
  const [loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reload,setReload]=useState(0);
  const [title,setTitle]=useState('Встречи с организациями'),[startAt,setStartAt]=useState(()=>nextWeekdayStart());
  const [meetingMinutes,setMeetingMinutes]=useState(45),[bufferMinutes,setBufferMinutes]=useState(15),[speedKmh,setSpeedKmh]=useState(30),[detourFactor,setDetourFactor]=useState(1.4),[optimize,setOptimize]=useState(true),[managerId,setManagerId]=useState('');
  const [startLon,setStartLon]=useState(''),[startLat,setStartLat]=useState(''),[shareCoordinates,setShareCoordinates]=useState(false);
  useEffect(()=>{const timer=setTimeout(()=>{setSearch(query);setOffset(0);},300);return()=>clearTimeout(timer);},[query]);
  useEffect(()=>{setData(null);setSelected([]);setEditing(null);setPreview(null);setError('');setNotice('');setShareCoordinates(false);},[mode]); // Root clears the map when modes change; opening this panel must preserve an existing route.
  useEffect(()=>{if(mode==='public')return;const controller=new AbortController();setLoading(true);setError('');read<PlanningPayload>(`/api/planning?mode=work&q=${encodeURIComponent(search)}&offset=${offset}`,{signal:controller.signal}).then(setData).catch(error=>{if(!controller.signal.aborted)setError(error.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[mode,search,offset,reload]);
  useEffect(()=>{if(mode==='public'||!initialOrganizationId)return;const controller=new AbortController();read<PlanningOrganization|null>(`/api/planning/${encodeURIComponent(initialOrganizationId)}?mode=work`,{signal:controller.signal}).then(setEditing).catch(()=>{});return()=>controller.abort();},[mode,initialOrganizationId]);
  function select(org:PlanningOrganization){setError('');setPreview(null);onRoute?.(null);setSelected(current=>current.some(item=>item.id===org.id)?current.filter(item=>item.id!==org.id):current.length<12?[...current,org]:current);}
  function move(index:number,delta:number){setSelected(current=>{const next=[...current];[next[index],next[index+delta]]=[next[index+delta],next[index]];return next;});setPreview(null);onRoute?.(null);}
  async function sync(){setBusy(true);setError('');try{const result=await post<{matched:number;retainedManual:number;candidates:number}>('/api/organization-locations/sync',{mode:'work'});setNotice(`Сопоставлено по ИНН: ${result.matched}. Кандидатов: ${result.candidates}. Ручных подтверждений сохранено: ${result.retainedManual}.`);setReload(value=>value+1);}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  async function build(){setBusy(true);setError('');try{let startCoordinates:Coordinates|null=null;if(startLon.trim()||startLat.trim()){if(!startLon.trim()||!startLat.trim())throw new Error('Заполните обе координаты начальной точки.');startCoordinates=[Number(startLon.replace(',','.')),Number(startLat.replace(',','.'))];if(!startCoordinates.every(Number.isFinite))throw new Error('Проверьте координаты начальной точки.');}
    const input:PlanInput={title,orgIds:selected.map(org=>org.id),startAt,meetingMinutes,bufferMinutes,speedKmh,detourFactor,optimize,startCoordinates,managerId:managerId||null};
    const plan=await post<MeetingPlan>('/api/plans',{mode:'work',...input});setPreview(plan);setShareCoordinates(false);setNotice('План сохранён локально. Встречи ещё нужно согласовать.');setReload(value=>value+1);
  }catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  async function roads(){if(!preview)return;setBusy(true);setError('');try{const plan=await post<MeetingPlan>(`/api/plans/${encodeURIComponent(preview.id)}/road`,{mode:'work',shareCoordinates:true});setPreview(plan);setReload(value=>value+1);}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  if(mode==='public')return <section className="planning-panel planning-empty"><ShieldCheck size={28}/><h3>Планирование встреч</h3><p>Адреса клиентов, возможности и маршруты доступны в рабочем режиме и сохраняются на этом компьютере.</p>{onRequestWork&&<button className="planning-action" onClick={onRequestWork}>Перейти в рабочий режим</button>}</section>;
  const items=locatedOnly?(data?.locatedOrganizations||[]).filter(org=>!query||`${org.name} ${org.inn}`.toLocaleLowerCase('ru-RU').includes(query.toLocaleLowerCase('ru-RU'))):data?.organizations||[];
  return <section className="planning-panel">
    <div className="planning-tabs" aria-label="Разделы планирования"><button aria-pressed={tab==='organizations'} onClick={()=>setTab('organizations')}>Организации</button><button aria-pressed={tab==='plan'} onClick={()=>setTab('plan')}>План дня{selected.length>0&&` · ${selected.length}`}</button></div>
    {error&&<p className="planning-error" role="alert">{error} <button onClick={()=>setReload(value=>value+1)}>Повторить</button></p>}{notice&&<p className="planning-notice" role="status">{notice}</p>}
    {snapshot!=='current'&&<p className="planning-note">Возможности и закрепление КМ показаны по последнему срезу, независимо от выбранного квартала карты.</p>}
    {tab==='organizations'&&<>
      {!editing&&<>
      <label className="planning-search"><Search size={17}/><input aria-label="Найти организацию по названию или ИНН" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Организация или ИНН"/></label>
      <div className="planning-tools"><label><input type="checkbox" checked={locatedOnly} onChange={event=>setLocatedOnly(event.target.checked)}/> С найденными адресами</label><button onClick={sync} disabled={busy}>Сопоставить источники</button></div>
      {loading&&!data?<p className="planning-note" role="status">Читаем организации…</p>:!items.length?<div className="planning-empty"><MapPin size={25}/><p>{locatedOnly?'В открытых источниках пока нет сопоставленных адресов. Найдите организацию и подтвердите её адрес вручную.':'Организации не найдены. Измените запрос или импортируйте источники.'}</p></div>:<ul className="planning-organizations">{items.map(org=><li key={org.id}>
        <label className="planning-pick"><input type="checkbox" checked={selected.some(item=>item.id===org.id)} disabled={selected.length>=12&&!selected.some(item=>item.id===org.id)} onChange={()=>select(org)}/><span><strong>{org.name}</strong><small>ИНН {org.inn} · {locationLabels[org.geoStatus]}</small></span></label>
        <p>{pointLabel(org)}</p><div className="planning-row-actions"><button onClick={()=>setEditing(org)}>Адрес и возможности</button><span>{org.opportunities.length?`${org.opportunities.length} повода для встречи`:'Недостаточно данных для правил'}</span></div>
      </li>)}</ul>}
      {!locatedOnly&&data&&<div className="planning-pagination"><button disabled={offset===0||loading} onClick={()=>setOffset(Math.max(0,offset-40))}>Назад</button><span>{data.total?`${offset+1}–${Math.min(offset+40,data.total)} из ${data.total.toLocaleString('ru-RU')}`:'0 организаций'}</span><button disabled={offset+40>=data.total||loading} onClick={()=>setOffset(offset+40)}>Далее</button></div>}
      </>}
      {editing&&<button className="planning-secondary planning-full" disabled={selected.length>=12&&!selected.some(org=>org.id===editing.id)} onClick={()=>select(editing)}>{selected.some(org=>org.id===editing.id)?'Убрать из плана':'Добавить организацию в план'}</button>}
      {editing&&<AddressEditor key={editing.id} org={editing} onClose={()=>setEditing(null)} onOpenOrganization={onOrganization?()=>onOrganization(editing.id):undefined} onSaved={async()=>{setReload(value=>value+1);const updated=await read<PlanningOrganization>(`/api/planning/${encodeURIComponent(editing.id)}?mode=work`);setEditing(updated);setSelected(current=>current.map(org=>org.id===updated.id?updated:org));setPreview(null);onRoute?.(null);}}/>}
      {selected.length>0&&<button className="planning-action planning-full" onClick={()=>setTab('plan')}><CalendarClock size={17}/>Составить план · {selected.length}</button>}
    </>}
    {tab==='plan'&&<>
      {!selected.length?<p className="planning-note">Выберите организации во вкладке «Организации». Для маршрута нужен подтверждённый адрес офиса или места встречи.</p>:<ol className="planning-stop-picker">{selected.map((org,index)=><li key={org.id}><span>{index+1}</span><div><strong>{org.name}</strong><small>{pointLabel(org)}</small></div><button aria-label={`Поднять ${org.name}`} disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp size={16}/></button><button aria-label={`Опустить ${org.name}`} disabled={index===selected.length-1} onClick={()=>move(index,1)}><ArrowDown size={16}/></button><button aria-label={`Убрать ${org.name}`} onClick={()=>select(org)}><X size={16}/></button></li>)}</ol>}
      <div className="planning-form"><label>Название плана<input value={title} onChange={event=>setTitle(event.target.value)} maxLength={200}/></label><label>Начало · Москва (UTC+3)<input type="datetime-local" value={startAt} onChange={event=>setStartAt(event.target.value)}/></label>
        <div className="planning-columns"><label>Встреча, мин<input type="number" min={10} max={240} value={meetingMinutes} onChange={event=>setMeetingMinutes(Number(event.target.value))}/></label><label>Буфер, мин<input type="number" min={0} max={120} value={bufferMinutes} onChange={event=>setBufferMinutes(Number(event.target.value))}/></label></div>
        <label>Ответственный КМ<select value={managerId} onChange={event=>setManagerId(event.target.value)}><option value="">По закреплению, если известно</option>{data?.managers.map(manager=><option key={manager.id} value={manager.id}>{manager.name}</option>)}</select></label>
        <label className="planning-check"><input type="checkbox" checked={optimize} onChange={event=>setOptimize(event.target.checked)}/> Упорядочить по ближайшей следующей точке</label>
        <details><summary>Начальная точка и параметры оценки</summary><p className="planning-note">Без начальной точки отсчёт начинается у первой организации. Коэффициент и скорость — ваши предположения для предварительного плана.</p><div className="planning-columns"><label>Долгота старта<input inputMode="decimal" value={startLon} onChange={event=>setStartLon(event.target.value)} placeholder="49.12"/></label><label>Широта старта<input inputMode="decimal" value={startLat} onChange={event=>setStartLat(event.target.value)} placeholder="55.79"/></label><label>Скорость, км/ч<input type="number" min={5} max={100} value={speedKmh} onChange={event=>setSpeedKmh(Number(event.target.value))}/></label><label>Коэффициент объезда<input type="number" min={1} max={3} step={0.1} value={detourFactor} onChange={event=>setDetourFactor(Number(event.target.value))}/></label></div></details>
      </div><button className="planning-action planning-full" onClick={build} disabled={busy||!selected.length}><Route size={17}/>{busy?'Рассчитываем…':'Рассчитать и сохранить план'}</button>
      {preview&&<div className="planning-preview"><div className="planning-preview-head"><h3>{preview.title}</h3><button aria-label="Убрать маршрут с карты" onClick={()=>{setPreview(null);onRoute?.(null);}}><X size={17}/></button></div><p><strong>{preview.totalDistanceKm.toLocaleString('ru-RU')} км · {preview.totalTravelMinutes} мин в пути</strong></p><p className="planning-note">{preview.methodLabel}. {preview.manager?`КМ: ${preview.manager.name}.`:'КМ не определён.'}</p><ol className="planning-timeline">{preview.stops.map(stop=><li key={stop.orgId}><time>{clock(stop.arrivalAt)}–{clock(stop.meetingEndsAt)}</time><strong>{stop.name}</strong><p>{stop.address}</p><small>Дорога: {stop.travelMinutes} мин · буфер после встречи: {stop.bufferMinutes} мин</small>{stop.warnings.map(note=><p className="planning-note" key={note}>{note}</p>)}</li>)}</ol>
        {preview.warnings.map(note=><p className="planning-note" key={note}>{note}</p>)}{preview.routingError&&<p className="planning-error" role="status">{preview.routingError}</p>}
        <div className="planning-road"><label className="planning-check"><input type="checkbox" checked={shareCoordinates} onChange={event=>setShareCoordinates(event.target.checked)}/> Передать только координаты выбранных точек сервису OSRM. Названия, ИНН и суммы не отправляются.</label><button className="planning-secondary" disabled={busy||!shareCoordinates||preview.stops.length>8} onClick={roads}>Уточнить по дорогам · OSRM</button><small>До 8 встреч. Дорожное время без пробок; согласование встреч выполняется отдельно.</small></div>
        {onRoute&&<button className="planning-action planning-full" onClick={()=>onRoute(preview)}><Route size={17}/>Показать маршрут на карте</button>}
      </div>}
      {!!data?.plans.length&&<details className="planning-saved"><summary>Сохранённые планы · {data.plans.length}</summary>{data.plans.map(plan=><button key={plan.id} onClick={()=>{setPreview(plan);setShareCoordinates(false);}}><span>{plan.title}</span><small>{new Date(plan.startAt).toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'})} · {plan.stops.length} встреч · {plan.method==='road'?'по дорогам':'оценка'}</small></button>)}</details>}
    </>}
  </section>;
}

function AddressEditor({org,onClose,onSaved,onOpenOrganization}:{org:PlanningOrganization;onClose:()=>void;onSaved:()=>Promise<void>;onOpenOrganization?:()=>void}){
  const editor=useRef<HTMLElement>(null);
  const [kind,setKind]=useState<'legal'|'office'|'meeting'>('meeting'),[address,setAddress]=useState(''),[lon,setLon]=useState(''),[lat,setLat]=useState(''),[precision,setPrecision]=useState<Precision>('building'),[sourceUrl,setSourceUrl]=useState(''),[confirmed,setConfirmed]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
  function fill(point:LocationPoint|null|undefined,nextKind=kind){setKind(nextKind);setAddress(point?.address||'');setLon(point?.coordinates?String(point.coordinates[0]):'');setLat(point?.coordinates?String(point.coordinates[1]):'');setPrecision(point?.precision||'building');setSourceUrl(point?.sourceUrl||'');setConfirmed(false);setSaved(false);}
  useEffect(()=>{fill(org.location?.meeting);editor.current?.scrollIntoView({block:'start',behavior:'auto'});},[org.id]);
  async function save(){setSaving(true);setError('');setSaved(false);try{let coordinates:Coordinates|null=null;if(lon.trim()||lat.trim()){if(!lon.trim()||!lat.trim())throw new Error('Укажите обе координаты.');coordinates=[Number(lon.replace(',','.')),Number(lat.replace(',','.'))];if(!coordinates.every(Number.isFinite))throw new Error('Координаты должны быть числами.');}await post('/api/organization-locations',{mode:'work',orgId:org.id,kind,address,coordinates,precision,sourceUrl,confirmed});await onSaved();setSaved(true);}catch(error){setError((error as Error).message);}finally{setSaving(false);}}
  const candidates=org.location?.candidates||[];
  return <section ref={editor} className="planning-editor"><div className="planning-preview-head"><h3>{org.name}</h3><button aria-label="Вернуться к списку организаций" onClick={onClose}><X size={18}/></button></div><p className="planning-note">ИНН {org.inn}. {org.location?.note}</p>
    {org.location?.legalAddress&&<div className="planning-address-source"><strong>Юридический адрес</strong><p>{org.location.legalAddress.address}</p>{org.location.legalAddress.note&&<p className="planning-note">{org.location.legalAddress.note}</p>}{org.location.legalAddress.sourceUrl&&<a href={org.location.legalAddress.sourceUrl} target="_blank" rel="noreferrer">Первоисточник</a>}<button onClick={()=>fill(org.location?.legalAddress,'meeting')}>Проверить как место встречи</button></div>}
    {org.location?.office&&<div className="planning-address-source"><strong>Адрес офиса / учреждения</strong><p>{org.location.office.address}</p>{org.location.office.note&&<p className="planning-note">{org.location.office.note}</p>}{org.location.office.sourceUrl&&<a href={org.location.office.sourceUrl} target="_blank" rel="noreferrer">Первоисточник</a>}<button onClick={()=>fill(org.location?.office,'meeting')}>Проверить место встречи</button></div>}
    {candidates.length>0&&<details><summary>Кандидаты адреса · {candidates.length}</summary>{candidates.map((candidate:AddressCandidate)=><div className="planning-candidate" key={candidate.id}><p>{candidate.name}<br/>{candidate.address}</p>{candidate.note&&<p className="planning-note">{candidate.note}</p>}<a href={candidate.sourceUrl} target="_blank" rel="noreferrer">Источник</a><button onClick={()=>fill(candidate,'meeting')}>Проверить кандидата</button></div>)}</details>}
    <div className="planning-form"><label>Назначение адреса<select value={kind} onChange={event=>{const next=event.target.value as typeof kind;fill(org.location?.[next==='legal'?'legalAddress':next],next);}}><option value="meeting">Место встречи</option><option value="office">Адрес офиса</option><option value="legal">Юридический адрес</option></select></label><label>Адрес<input value={address} onChange={event=>{setAddress(event.target.value);setConfirmed(false);}} maxLength={1000}/></label><div className="planning-columns"><label>Долгота<input inputMode="decimal" value={lon} onChange={event=>{setLon(event.target.value);setConfirmed(false);}} placeholder="49.12"/></label><label>Широта<input inputMode="decimal" value={lat} onChange={event=>{setLat(event.target.value);setConfirmed(false);}} placeholder="55.79"/></label></div><label>Точность<select value={precision} onChange={event=>{setPrecision(event.target.value as Precision);setConfirmed(false);}}><option value="building">Здание / вход</option><option value="street">Улица</option><option value="settlement">Населённый пункт</option><option value="territory">Территория</option><option value="site">Участок / площадка</option></select></label><label>Ссылка на источник, если есть<input type="url" value={sourceUrl} onChange={event=>{setSourceUrl(event.target.value);setConfirmed(false);}} placeholder="https://…"/></label><label className="planning-check"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/> Проверил организацию, адрес и точность координат. Место встречи отличается от юридического адреса, если это необходимо.</label></div>
    {error&&<p className="planning-error" role="alert">{error}</p>}{saved&&<p className="planning-notice" role="status"><Check size={16}/> Адрес сохранён локально.</p>}<button className="planning-secondary planning-full" disabled={saving||!confirmed||!address.trim()} onClick={save}>{saving?'Сохраняем…':'Подтвердить и сохранить адрес'}</button>
    <div className="planning-opportunities"><h3>Поводы для встречи</h3>{org.opportunities.length?org.opportunities.map(item=><details key={item.id}><summary>{item.title}</summary><strong>Факты из источников</strong><ul>{item.facts.map(fact=><li key={fact}>{fact}</li>)}</ul><p><strong>Гипотеза.</strong> {item.hypothesis}</p><p><strong>Для обсуждения:</strong> {item.products.join(', ')}.</p><p><strong>Следующий шаг.</strong> {item.nextStep}</p><small>Применимость и условия продукта требуют проверки; это не одобрение или лимит.</small>{item.sourceLabels.map(source=><small key={source}>{source.startsWith('https://')?<a href={source} target="_blank" rel="noreferrer">Справка о продукте</a>:source}</small>)}</details>):<p className="planning-note">Недостаточно заполненных данных для правил. Это не означает отсутствия потребности у клиента.</p>}</div>
    {onOpenOrganization&&<button className="planning-secondary planning-full" onClick={onOpenOrganization}>Открыть полную карточку</button>}
  </section>;
}
