'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, BarChart3, Building2, MapPin, RefreshCw, X } from 'lucide-react';
import type { TerritoryAnalytics as Analytics } from '@/lib/territory-analytics';
import { SNAPSHOTS, type Mode } from '@/lib/types';
import { money, number, shortDate } from '@/lib/format';
import { safeSourceUrl } from '@/lib/territory-scope';
import IncidentRecords from './IncidentRecords';
import styles from './TerritoryAnalytics.module.css';
const percent = (n: number | null) => n === null ? '—' : `${n.toLocaleString('ru-RU', { maximumFractionDigits: 1 })}%`;
const bankNames: Record<string, string> = { sber: 'Сбер', vtb: 'ВТБ', akbars: 'Ак Барс', psb: 'ПСБ', gazprombank: 'Газпромбанк', gpb: 'Газпромбанк' };
function Metric({ label, value, note }: { label: string; value: string; note?: string }) {
  return <div className={styles.metric}><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>;
}
export default function TerritoryAnalytics({ mode, initialTerritory, initialTab = 'territory', onClose, onMap, onOrganization, onPlan, onSignal, onSources, onClients }: {
  mode: Mode; initialTerritory: string; initialTab?: 'territory' | 'sber'; onClose: () => void; onMap: (id: string) => void;
  onOrganization: (id: string) => void; onPlan: (id: string) => void; onSignal: (id: string) => void; onSources: () => void; onClients: () => void;
}) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [territory, setTerritory] = useState(initialTerritory), [tab, setTab] = useState(initialTab), [days, setDays] = useState(45), [snapshot, setSnapshot] = useState('current');
  const [data, setData] = useState<Analytics | null>(null), [error, setError] = useState(''), [version, setVersion] = useState(0), [records, setRecords] = useState(false);
  useEffect(() => { const element = dialog.current; element?.showModal(); return () => element?.close(); }, []);
  useEffect(() => {
    const c = new AbortController(); setData(null); setError(''); setRecords(false);
    fetch(`/api/analytics?${new URLSearchParams({ mode, territory, days: String(days), snapshot })}`, { signal: c.signal, cache: 'no-store' })
      .then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Не удалось получить аналитику'); return d as Analytics; })
      .then(d => { if (!c.signal.aborted) setData(d); }).catch(e => { if (!c.signal.aborted) setError(e.message); });
    return () => c.abort();
  }, [mode, territory, days, snapshot, version]);
  const c = data?.complaints, p = data?.portfolio;
  return <dialog ref={dialog} className={styles.panel} aria-labelledby="analytics-heading" onCancel={onClose} onClick={e => { if (e.target === dialog.current) onClose(); }}>
    <header className={styles.head}><div><span className={styles.eyebrow}>Сбер Атлас · Аналитика</span><h2 id="analytics-heading">{data?.territory.name || 'Аналитика территории'}</h2></div><button aria-label="Закрыть аналитику" onClick={onClose}><X size={23}/></button></header>
    <div className={styles.controls}>
      <div className={styles.tabs} aria-label="Раздел аналитики"><button aria-pressed={tab === 'territory'} onClick={() => setTab('territory')}><BarChart3 size={17}/>Территория</button><button aria-pressed={tab === 'sber'} onClick={() => setTab('sber')}><Building2 size={17}/>Для Сбера</button></div>
      <label>Публичные сигналы<select aria-label="Период публичных сигналов" value={days} onChange={e => setDays(Number(e.target.value))}>{[30,45,60,180].map(n => <option key={n} value={n}>{n} дней</option>)}</select></label>
      {tab === 'sber' && mode === 'work' && <label>Срез портфеля<select aria-label="Срез аналитического портфеля" value={snapshot} onChange={e => setSnapshot(e.target.value)}>{SNAPSHOTS.map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</select></label>}
      <button aria-label="Обновить аналитику" onClick={() => setVersion(n => n + 1)}><RefreshCw size={18}/></button>
    </div>
    <div className={styles.body}>
      {error ? <div role="alert" className={styles.empty}><h3>{error}</h3><button onClick={() => { setTerritory('RU-TA'); setVersion(n => n + 1); }}>Открыть подключённый регион</button></div> : !data ? <div role="status" className={styles.empty}>Рассчитываем сводку по всем загруженным данным…</div> : <>
        <div className={styles.scope}><div>{data.ancestors[0] && <button onClick={() => setTerritory(data.ancestors[0].id)}><ArrowLeft size={15}/>{data.ancestors[0].name}</button>}<label>Территория<select aria-label="Территория аналитики" value={territory} onChange={e => setTerritory(e.target.value)}>{data.territories.map(t => <option key={t.id} value={t.id}>{t.name}{t.oktmo ? ` · ${t.oktmo}` : ''}</option>)}</select></label></div><button onClick={() => onMap(territory)}><MapPin size={16}/>Показать на карте</button></div>
        {data.privateError && <aside className={styles.notice}>{data.privateError} <button onClick={onSources}>Подключить источники</button></aside>}
        {tab === 'territory' ? <>
          <section className={styles.section}><div className={styles.sectionTitle}><h3>Обращения жителей</h3>{c && <span>{shortDate(c.firstAt)} — {shortDate(c.lastAt)} · исторический срез</span>}</div>
            {c ? <><div className={styles.metrics}><Metric label="Всего в выгрузке" value={number(c.total)}/><Metric label="Незакрытые" value={number(c.open)} note={`Из них в работе: ${number(c.inProgress)}`}/><Metric label="Закрытые" value={number(c.closed)} note={`Неизвестный статус: ${number(c.unknown)}`}/><Metric label="Индекс незакрытых" value={percent(c.index)} note={`${number(c.open + c.closed)} записей с известным статусом`}/></div>
              <details className={styles.method}><summary>Как читать индекс</summary><p>100 × незакрытые / (незакрытые + закрытые). «В работе» входит в незакрытые. Неизвестные статусы не попадают в знаменатель. Это состояние выгрузки, не оценка ситуации сегодня и не рейтинг благополучия. Без населения нельзя сравнивать число жалоб на жителя. Малые выборки нестабильны.</p><p>Источник: {c.source}. Импорт: {shortDate(c.importedAt)}. Дата обращения неизвестна у {number(c.unknownDates)} записей.</p></details>
              <div className={styles.columns}><div><h4>Темы, требующие внимания</h4>{c.topics.slice(0, 8).map(t => <div className={styles.barRow} key={t.name}><div><span>{t.name}</span><strong>{number(t.open)} / {number(t.total)}</strong></div><div className={styles.track}><i style={{ width: `${c.total ? 100 * t.total / c.total : 0}%` }}/></div></div>)}<p className={styles.caption}>Незакрытые / всего по теме. Длина полосы — доля всех записей.</p></div><div><h4>Поступление по месяцам</h4>{c.months.map(m => <div className={styles.barRow} key={m.month}><div><span>{m.month}</span><strong>{number(m.count)}</strong></div><div className={styles.track}><i style={{ width: `${100 * m.count / Math.max(1, ...c.months.map(x => x.count))}%` }}/></div></div>)}<p className={styles.caption}>Количество по дате создания. Это не динамика текущего остатка; полнота крайних месяцев неизвестна.</p></div></div>
              <button className={styles.link} onClick={() => setRecords(v => !v)}>{records ? 'Скрыть исходные записи' : 'Раскрыть до обращений'}<ArrowUpRight size={15}/></button>{records && <div className={styles.records}><IncidentRecords key={territory} territoryId={territory}/></div>}
            </> : <div className={styles.empty}>Обращения доступны только из подключённой локальной выгрузки в рабочем режиме. Публичные новости не заменяют жалобы жителей.<button onClick={onSources}>Источники и импорт</button></div>}
          </section>
          <section className={styles.section}><div className={styles.sectionTitle}><h3>Публичная повестка</h3><span>Публикации за {days} дней</span></div><div className={styles.metrics}><Metric label="События" value={number(data.signals.count)}/><Metric label="Сообщения / проблемы" value={number(data.signals.problems)}/><Metric label="Работы и планы" value={number(data.signals.work)}/><Metric label="Результаты" value={number(data.signals.results)}/></div><p className={styles.caption}>Считаются события из полной ленты, не число жалоб и не количество перепечаток. Нулевой счётчик не доказывает отсутствие событий. {data.signals.coverage ? `Покрытие: ${data.signals.coverage.level === 'direct' ? 'прямые источники' : data.signals.coverage.level === 'missing' ? 'нет подтверждённого покрытия' : 'унаследованные источники'}.` : 'Полнота источников этой территории не подтверждена.'}</p>
            <div className={styles.feed}>{data.signals.items.slice(0, 8).map(s => <article key={s.id}><button onClick={() => onSignal(s.id)}>{s.title}<ArrowUpRight size={15}/></button><small>{shortDate(s.publishedAt)} · {s.sourceName || 'Публичный источник'}</small>{safeSourceUrl(s.sourceUrl) && <a href={s.sourceUrl} target="_blank" rel="noreferrer">Открыть источник</a>}</article>)}</div>
          </section>
        </> : <>
          <section className={styles.section}><div className={styles.sectionTitle}><h3>Банковское присутствие</h3><span>Наблюдаемая сеть, не доля рынка</span></div><div className={styles.metrics}><Metric label="Подтверждённые точки" value={number(data.priority.numbers.verifiedLocations)}/><Metric label="Сбер" value={number(data.priority.numbers.verifiedSberLocations)}/><Metric label="Другие банки" value={number(data.priority.numbers.verifiedCompetitorLocations)}/><Metric label="Сбер в доступной сети" value={percent(data.sberShare)}/></div><div className={styles.bankList}>{data.banks.map(b => <div className={styles.barRow} key={b.bank}><div><span>{bankNames[b.bank] || b.bank}</span><strong>{number(b.count)}</strong></div><div className={styles.track}><i style={{ width: `${data.priority.numbers.verifiedLocations ? 100 * b.count / data.priority.numbers.verifiedLocations : 0}%` }}/></div><small>Неактуальных: {b.stale} · без достаточной географии: {b.missing}</small></div>)}</div><p className={styles.caption}>Объединены повторы источников по одному банку и месту. Учитывается подтверждённая география с проверкой не старше 365 дней, но не режим работы. Полнота банковской сети неизвестна.</p></section>
          <section className={styles.section}><div className={styles.sectionTitle}><h3>Клиентский портфель</h3><button onClick={onClients}>Все клиенты и возможности<ArrowUpRight size={15}/></button></div>{p ? <><p className={styles.caption}>{p.sourceLabel}</p><div className={styles.metrics}><Metric label="Клиенты в территории" value={number(p.summary.organizations)} note={`${number(p.summary.uniqueInns)} уникальных ИНН`}/><Metric label="Предложения" value={p.offersAvailable ? number(p.summary.offers) : '—'} note="В выбранном срезе"/><Metric label="Ожидаемый доход" value={money(p.summary.income)} note={`Без ОД: ${number(p.summary.missingIncome)} предложений`}/><Metric label="Будущие планы" value={number(p.summary.plannedClients)} note="Клиенты в локальных планах; не согласованные встречи"/></div><aside className={styles.notice}>На этой территории учтены только организации с подтверждёнными координатами. Во всём портфеле: {number(p.all.organizations)} записей, известный ОД {money(p.all.income)}; без распределения по территории: {number(p.unassigned.organizations)} записей, ОД {money(p.unassigned.income)}. Суммы не разнесены по районам пропорционально населению или ГОСБ.</aside>
            <div className={styles.columns}><div><h4>Зарплатные выплаты</h4><p>Март: <b>{money(p.summary.payrollMarch)}</b> · июль: <b>{money(p.summary.payrollJuly)}</b></p><p>Изменение: <b>{percent(p.summary.payrollGrowth)}</b> · сопоставимых клиентов: {number(p.summary.payrollComparableClients)}.</p><p className={styles.caption}>Только одна и та же группа с двумя известными суммами. Изменение выплат не доказывает изменение штата.</p></div><div><h4>Контактная работа</h4>{p.summary.meetingCounts.map((n, i) => <p key={i}>{['I','II','III'][i]} квартал: <b>{number(n)}</b><small> · данные у {number(p.summary.meetingKnown[i])} клиентов</small></p>)}<p className={styles.caption}>Счётчики из выгрузки. Конфликтующие и неизвестные значения не заменены нулями; уникальность встреч между кварталами не доказана.</p></div></div>
            <details className={styles.method}><summary>Качество и методика</summary>{p.notes.map(n => <p key={n}>{n}</p>)}<p>Повторов предложений исключено: {p.summary.duplicateOffers}. Строк с неоднозначными ID: {p.summary.ambiguousOffers}.</p></details>
            <h4>Следующие действия</h4>{p.actions.length ? <div className={styles.actionGrid}>{p.actions.map(r => <article key={r.id}><button onClick={() => onOrganization(r.id)}><strong>{r.name}</strong><ArrowUpRight size={15}/></button><small>ИНН {r.inn} · {r.offers} предложений</small>{r.actions.slice(0, 2).map(a => <div key={a.rule + (a.signalId || '')}><h5>{a.title}</h5><p>{a.facts[0]}</p><p className={styles.caption}>{a.nextStep}</p></div>)}<button className={styles.link} onClick={() => onPlan(r.id)}>Подготовить встречу</button></article>)}</div> : <p className={styles.caption}>Подтверждённых поводов по размещённым здесь клиентам пока нет. Проверьте адреса и состав источников.</p>}</> : <div className={styles.empty}>Внутренние сделки, ФОТ и встречи доступны только локально в рабочем режиме.<button onClick={onSources}>Источники и режим доступа</button></div>}</section>
          <section className={styles.section}><div className={styles.sectionTitle}><h3>Приоритет проверки территории</h3><b>{data.priority.score === null ? 'Недостаточно данных' : `${data.priority.score} баллов`}</b></div>{data.priority.facts.map(f => <p key={f}>{f}</p>)}<aside className={styles.notice}>{data.priority.nextStep}</aside><details className={styles.method}><summary>Из чего складывается приоритет</summary><p>{data.priority.note}</p>{data.priority.sources.map(s => <p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.label}</a> · {shortDate(s.asOf)}</p>)}</details></section>
        </>}
        {data.children.length > 0 && <section className={styles.section}><div className={styles.sectionTitle}><h3>Территории внутри</h3><span>Нажмите строку для детализации</span></div><p className={styles.caption}>Сравнивайте территории одного административного уровня. Записи, известные только на уровне родителя, не распределяются между детьми.{c ? ` На уровне родителя осталось ${number(c.unassignedWithinScope)} обращений.` : ''}</p><div className={styles.tableWrap}><table><thead><tr><th>Территория</th><th>Незакрытые</th><th>Индекс</th><th>Сигналы</th><th>Сбер / сеть</th>{tab === 'sber' && <th>Предложения / ОД</th>}</tr></thead><tbody>{data.children.map(row => <tr key={row.territory.id}><th><button onClick={() => setTerritory(row.territory.id)}>{row.territory.name}</button></th><td>{number(row.complaints?.open)}</td><td>{percent(row.complaints?.index ?? null)}<small>n={number(row.complaints ? row.complaints.open + row.complaints.closed : null)}</small></td><td>{number(row.signals)}</td><td>{number(row.sber)} / {number(row.banks)}</td>{tab === 'sber' && <td>{row.portfolio ? `${row.portfolio.offers} / ${money(row.portfolio.income)}` : '—'}</td>}</tr>)}</tbody></table></div></section>}
        <footer className={styles.footer}>Расчёт: {shortDate(data.asOf)}. <button onClick={onSources}>Источники, покрытие и импорт</button></footer>
      </>}
    </div>
  </dialog>;
}
